// src/api/mockData.js
// Development mock data — mirrors exact API response shapes

export const MOCK_FILES = {
  items: [
    {
      id: 'file-001',
      fileName: 'BLACKROCK_Q4_2024.csv',
      client: 'BlackRock',
      fileSize: '12.4 MB',
      uploadedAt: '2024-12-20T12:00:00Z',
      status: 'complete',
      totalRecords: 48320,
      totalErrors: 487,
      approvedCount: 0,
      pendingCount: 487,
      correctedCount: 0,
      rejectedCount: 0,
    },
    {
      id: 'file-002',
      fileName: 'VANGUARD_SEC_MASTER.xlsx',
      client: 'Vanguard',
      fileSize: '8.1 MB',
      uploadedAt: '2024-12-20T11:00:00Z',
      status: 'complete',
      totalRecords: 31050,
      totalErrors: 312,
      approvedCount: 45,
      pendingCount: 267,
      correctedCount: 12,
      rejectedCount: 0,
    },
    {
      id: 'file-003',
      fileName: 'JPMORGAN_TRADE_DATA.csv',
      client: 'JP Morgan',
      fileSize: '22.3 MB',
      uploadedAt: '2024-12-20T13:30:00Z',
      status: 'processing',
      totalRecords: 94100,
      totalErrors: null,
      approvedCount: 0,
      pendingCount: 0,
      correctedCount: 0,
      rejectedCount: 0,
    },
  ],
  total: 3,
  page: 1,
  pageSize: 20,
}

export const MOCK_CATEGORIES = [
  { name: 'Missing fields',     total: 98, pending: 85, approved: 10, corrected: 3,  rejected: 0 },
  { name: 'Invalid ISIN',       total: 76, pending: 60, approved: 12, corrected: 4,  rejected: 0 },
  { name: 'Price anomaly',      total: 64, pending: 50, approved: 8,  corrected: 6,  rejected: 0 },
  { name: 'Currency mismatch',  total: 58, pending: 40, approved: 15, corrected: 3,  rejected: 0 },
  { name: 'Duplicate records',  total: 47, pending: 40, approved: 5,  corrected: 2,  rejected: 0 },
  { name: 'Date format error',  total: 43, pending: 35, approved: 5,  corrected: 3,  rejected: 0 },
  { name: 'Stale price',        total: 38, pending: 32, approved: 4,  corrected: 2,  rejected: 0 },
  { name: 'Rating discrepancy', total: 35, pending: 30, approved: 3,  corrected: 2,  rejected: 0 },
  { name: 'FX rate error',      total: 28, pending: 25, approved: 2,  corrected: 1,  rejected: 0 },
]

export const MOCK_ERRORS = {
  items: [
    {
      id: 'err-001', category: 'Missing fields',
      errorDescription: 'Accrued interest field missing for 14 bond positions across 3 portfolios in Q4 period',
      originalValue: 'NULL', aiSolution: '0.043200',
      aiAnalysis: 'Pattern indicates upstream feed truncation after field 42 in the CSV pipeline. Affects all records where maturity > 10Y.',
      dataSource: 'Bloomberg / Portfolio feed v2.3', status: 'pending',
    },
    {
      id: 'err-002', category: 'Invalid ISIN',
      errorDescription: 'ISIN US38141G1040 fails checksum validation for Goldman Sachs equity position',
      originalValue: 'US38141G1040', aiSolution: 'US38141G1022',
      aiAnalysis: 'Check digit mismatch. Source system applied wrong Luhn algorithm variant.',
      dataSource: 'ANNA DB / Custodian feed', status: 'pending',
    },
    {
      id: 'err-003', category: 'Price anomaly',
      errorDescription: 'NAV price for PIMCO Income Fund shows 340% spike on 2024-12-18 vs prior 30-day average',
      originalValue: '38.2100', aiSolution: '11.2300',
      aiAnalysis: 'Outlier beyond 5-sigma threshold. Likely data vendor error — same spike pattern observed in Nov 2023.',
      dataSource: 'Refinitiv / Fund admin', status: 'pending',
    },
    {
      id: 'err-004', category: 'Currency mismatch',
      errorDescription: 'EUR positions reported in USD denomination for Deutsche Bank holdings — 23 records affected',
      originalValue: 'USD', aiSolution: 'EUR',
      aiAnalysis: 'FX flag CCY_CODE set to USD for all DB records. Vendor mapping error introduced Dec 2.',
      dataSource: 'Deutsche Bank custodian', status: 'approved',
    },
    {
      id: 'err-005', category: 'Duplicate records',
      errorDescription: 'Trade ID TRD-2024-889341 appears 3 times with identical timestamps but different broker codes',
      originalValue: '3 dupes', aiSolution: '1 record',
      aiAnalysis: 'Trade duplication from reconciliation job running twice after network timeout.',
      dataSource: 'OMS / Trade blotter', status: 'pending',
    },
    {
      id: 'err-006', category: 'Date format error',
      errorDescription: 'Settlement dates for 8 T+2 equity trades stored as YYYYDDMM instead of YYYYMMDD',
      originalValue: '20241812', aiSolution: '20241218',
      aiAnalysis: 'New data vendor API changed format in v4.1 without changelog notification.',
      dataSource: 'Euroclear feed', status: 'rejected',
    },
    {
      id: 'err-007', category: 'Stale price',
      errorDescription: 'Municipal bond CUSIP 13063BLH3 has not refreshed since 2024-11-30 — 19 trading days stale',
      originalValue: '98.2500', aiSolution: 'Pending broker quote',
      aiAnalysis: 'Thinly traded security. Market data vendor excludes illiquid munis from EOD batch.',
      dataSource: 'ICE Data Services', status: 'pending',
    },
    {
      id: 'err-008', category: 'Rating discrepancy',
      errorDescription: "Moody Aa3 conflicts with S&P AA- for Pfizer 2031 bond across 2 portfolios",
      originalValue: 'Aa3', aiSolution: 'AA-',
      aiAnalysis: 'Rating agencies diverged post-Oct change. Policy IPS-2023 mandates S&P as primary.',
      dataSource: 'Moody / S&P feeds', status: 'pending',
    },
    {
      id: 'err-009', category: 'Missing fields',
      errorDescription: 'Yield to maturity absent for 31 corporate bond positions causing duration miscalculation',
      originalValue: 'NULL', aiSolution: 'Calculated via IRR',
      aiAnalysis: 'YTM dropped in schema migration v6 → v7. Migration script missed nullable bond columns.',
      dataSource: 'Bond master v7', status: 'corrected',
    },
    {
      id: 'err-010', category: 'FX rate error',
      errorDescription: 'GBP/USD rate of 0.7831 used instead of correct 1.2710 for UK equity valuations on 12/19',
      originalValue: '0.7831', aiSolution: '1.2710',
      aiAnalysis: 'FX lookup used inverse rate. Code regression in hotfix HF-2024-089.',
      dataSource: 'Reuters FX / Risk system', status: 'pending',
    },
  ],
  total: 487,
  page: 1,
  pageSize: 20,
}
